#!/bin/bash
# Bootstrap a new project: clone repos, create AGENTS.md hierarchy, add tmux launcher
# Usage: new-project <company> <product> <vcs> <namespace> [repo1] [repo2] ...

set -e

if [ "$#" -lt 4 ]; then
  cat <<'USAGE'
Usage: new-project <company> <product> <vcs> <namespace> [repo1] [repo2] ...

Examples:
  new-project acme payments gitlab acme-group backend frontend
  new-project beta auth github beta-org api workers
  new-project personal sandbox local local mini-tool

Args:
  company:   short slug (e.g. "acme")
  product:   short slug (e.g. "payments")
  vcs:       gitlab | github | bitbucket | local
  namespace: org/group name on VCS, or "local" for local-only
  repos:     repo names to clone (optional)
USAGE
  exit 1
fi

CO="$1"; PROD="$2"; VCS="$3"; NS="$4"
shift 4
REPOS=("$@")

WORK=~/work
COMPANY_DIR="$WORK/$CO"
PRODUCT_DIR="$COMPANY_DIR/$PROD"
TPL=~/dotfiles/templates

mkdir -p "$PRODUCT_DIR"

# Company-level AGENTS.md (only if new company)
if [ ! -f "$COMPANY_DIR/AGENTS.md" ]; then
  CO="$CO" VCS="$VCS" NS="$NS" envsubst < "$TPL/AGENTS.md.company.tmpl" > "$COMPANY_DIR/AGENTS.md"
  echo "✓ $COMPANY_DIR/AGENTS.md"
fi

# Product-level AGENTS.md
CO="$CO" PROD="$PROD" REPOS="${REPOS[*]}" envsubst < "$TPL/AGENTS.md.product.tmpl" > "$PRODUCT_DIR/AGENTS.md"
echo "✓ $PRODUCT_DIR/AGENTS.md"

# Determine remote prefix
case "$VCS" in
  gitlab)    REMOTE="git@gitlab.com:$NS" ;;
  github)    REMOTE="git@github.com:$NS" ;;
  bitbucket) REMOTE="git@bitbucket.org:$NS" ;;
  local)     REMOTE="" ;;
  *)         echo "Unknown VCS: $VCS"; exit 1 ;;
esac

# Clone repos & create per-repo AGENTS.md
for repo in "${REPOS[@]}"; do
  if [ ! -d "$PRODUCT_DIR/$repo" ]; then
    if [ -n "$REMOTE" ]; then
      git clone "$REMOTE/$repo.git" "$PRODUCT_DIR/$repo" || { echo "Failed to clone $repo, skipping"; continue; }
    else
      mkdir -p "$PRODUCT_DIR/$repo" && (cd "$PRODUCT_DIR/$repo" && git init)
    fi
    echo "✓ cloned $repo"
  fi
  if [ ! -f "$PRODUCT_DIR/$repo/AGENTS.md" ]; then
    REPO="$repo" CO="$CO" PROD="$PROD" envsubst < "$TPL/AGENTS.md.repo.tmpl" > "$PRODUCT_DIR/$repo/AGENTS.md"
    echo "✓ $repo/AGENTS.md"
  fi
done

# Add tmux launcher function
LAUNCHER=~/dotfiles/shell/30-projects.zsh
[ ! -f "$LAUNCHER" ] && echo "# Project tmux launchers (auto-generated by new-project.sh)" > "$LAUNCHER"

if ! grep -q "^${PROD}() {" "$LAUNCHER"; then
  FIRST_REPO="${REPOS[0]:-}"
  cat >> "$LAUNCHER" <<EOF

${PROD}() {
  tmux kill-session -t ${PROD} 2>/dev/null
  tmux new -d -s ${PROD} -c ${PRODUCT_DIR}/${FIRST_REPO}
  tmux send-keys -t ${PROD}:0 'export CODEX_HOME=\$HOME/.codex-new; clear; codex' Enter
  tmux split-window -v -t ${PROD}:0 -c ${PRODUCT_DIR}/${FIRST_REPO}
  tmux send-keys -t ${PROD}:0.1 'git status; echo' Enter
  tmux attach -t ${PROD}
}
EOF
  echo "✓ added '${PROD}' launcher to shell/30-projects.zsh"
fi

# Document in COMMANDS.md
DOC=~/dotfiles/docs/COMMANDS.md
if ! grep -q "^## ${PROD}$" "$DOC"; then
  cat >> "$DOC" <<EOF

## ${PROD}
**Что:** Open tmux session for ${CO}/${PROD} product
**Запуск:** \`${PROD}\`
**Файлы:** \`${PRODUCT_DIR}/\`
**Repos:** ${REPOS[*]}
**Env:** \`CODEX_HOME=~/.codex-new\`
EOF
  echo "✓ documented in COMMANDS.md"
fi

echo ""
echo "✅ ${CO}/${PROD} bootstrapped"
echo ""
echo "Structure:"
ls "$PRODUCT_DIR"
echo ""
echo "Next: source ~/.zshrc && ${PROD}"
