set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g history-limit 100000
set -s escape-time 0
set-option -g allow-rename off
set -g set-titles on
set -g set-titles-string "🖥 #{session_name}: #{window_name}"
set -g pane-border-status top
set -g pane-border-format " #{pane_title} "
